/*
    Slang J2K Encoder v7 - Real Slang-generated CUDA kernels

    This host driver uses kernels generated by the Slang shader compiler
    from slang_dwt97_v7.slang. The kernels are portable across GPU backends
    (CUDA, SPIR-V, HLSL, Metal, WGSL).

    The Slang runtime uses __constant__ memory for GlobalParams_0 which
    contains RWStructuredBuffer pointers and a device-side Params_0 pointer.
*/

#include "slang_j2k_encoder.h"

/* Need the Slang CUDA prelude for RWStructuredBuffer etc. */
#define SLANG_CUDA_STRUCTURED_BUFFER_NO_COUNT
#include "../../tools/slang/include/slang-cuda-prelude.h"

#include <cuda_runtime.h>
#include <cstring>
#include <cmath>
#include <algorithm>
#include <vector>
#include <mutex>

static constexpr int NUM_DWT_LEVELS = 5;
static constexpr uint16_t J2K_SOC=0xFF4F,J2K_SIZ=0xFF51,J2K_COD=0xFF52;
static constexpr uint16_t J2K_QCD=0xFF5C,J2K_SOT=0xFF90,J2K_SOD=0xFF93,J2K_EOC=0xFFD9;


/* ===== Slang-generated types (must match generated code) ===== */

struct Params_0 {
    int width_0;
    int height_0;
    int stride_0;
    int n_0;
    float stepSize_0;
    int targetN_0;
};

struct GlobalParams_0 {
    RWStructuredBuffer<float> g_data_0;
    RWStructuredBuffer<float> g_tmp_0;
    RWStructuredBuffer<int> g_input_0;
    RWStructuredBuffer<unsigned char> g_encoded_0;
    Params_0* p_0;
};

/* The Slang kernels reference this symbol */
extern "C" __constant__ GlobalParams_0 SLANG_globalParams;

/* ===== Slang-generated kernel declarations ===== */
extern "C" __global__ void intToFloat();
extern "C" __global__ void dwtHorzSmem();
extern "C" __global__ void dwtHorz();
extern "C" __global__ void dwtVert();
extern "C" __global__ void quantEncode();


/* ===== Implementation ===== */

struct SlangJ2KEncoderImpl {
    /* Device buffers */
    float* d_data = nullptr;
    float* d_tmp = nullptr;
    int32_t* d_input = nullptr;
    uint8_t* d_encoded = nullptr;
    Params_0* d_params = nullptr;  /* device-side params */

    /* Pinned host */
    int32_t* h_input = nullptr;
    uint8_t* h_encoded = nullptr;

    size_t px = 0, enc_size = 0;
    cudaStream_t stream = nullptr;

    /* Pre-built header */
    std::vector<uint8_t> hdr;
    int cw=0, ch=0;

    bool init() {
        if (cudaStreamCreate(&stream) != cudaSuccess) return false;
        if (cudaMalloc(&d_params, sizeof(Params_0)) != cudaSuccess) return false;
        return true;
    }

    void ensure(int w, int h, size_t epc) {
        size_t n = size_t(w) * h;
        enc_size = epc;
        if (n <= px) return;
        cleanup_bufs();

        cudaMalloc(&d_data, n * sizeof(float));
        cudaMalloc(&d_tmp, n * sizeof(float));
        cudaMalloc(&d_input, n * sizeof(int32_t));
        cudaMalloc(&d_encoded, epc);
        cudaHostAlloc(&h_input, n * sizeof(int32_t), cudaHostAllocDefault);
        cudaHostAlloc(&h_encoded, epc * 3, cudaHostAllocDefault);
        px = n;
    }

    void set_global_params(int w, int h, int s, float step, int target_n) {
        /* Set up params on device */
        Params_0 params;
        params.width_0 = w;
        params.height_0 = h;
        params.stride_0 = s;
        params.n_0 = w * h;
        params.stepSize_0 = step;
        params.targetN_0 = target_n;
        cudaMemcpy(d_params, &params, sizeof(Params_0), cudaMemcpyHostToDevice);

        /* Set up GlobalParams_0 and copy to __constant__ memory */
        GlobalParams_0 gp;
        gp.g_data_0.data = d_data;
        gp.g_tmp_0.data = d_tmp;
        gp.g_input_0.data = reinterpret_cast<int*>(d_input);
        gp.g_encoded_0.data = d_encoded;
        gp.p_0 = d_params;
        cudaMemcpyToSymbol(SLANG_globalParams, &gp, sizeof(GlobalParams_0));
    }

    /* Swap data<->tmp pointers and update global params */
    void swap_data_tmp() {
        float* t = d_data; d_data = d_tmp; d_tmp = t;
        /* Update the globalParams to reflect swapped pointers */
        GlobalParams_0 gp;
        cudaMemcpyFromSymbol(&gp, SLANG_globalParams, sizeof(GlobalParams_0));
        gp.g_data_0.data = d_data;
        gp.g_tmp_0.data = d_tmp;
        cudaMemcpyToSymbol(SLANG_globalParams, &gp, sizeof(GlobalParams_0));
    }

    /* Update just width/height in params (for DWT levels) */
    void update_params_wh(int w, int h) {
        Params_0 params;
        cudaMemcpy(&params, d_params, sizeof(Params_0), cudaMemcpyDeviceToHost);
        params.width_0 = w;
        params.height_0 = h;
        params.n_0 = w * h;
        cudaMemcpy(d_params, &params, sizeof(Params_0), cudaMemcpyHostToDevice);
    }

    void build_hdr(int w,int h){
        if(w==cw&&h==ch) return; cw=w;ch=h; hdr.clear();
        auto w8=[&](uint8_t v){hdr.push_back(v);};
        auto w16=[&](uint16_t v){hdr.push_back(v>>8);hdr.push_back(v&0xFF);};
        auto w32=[&](uint32_t v){w16(v>>16);w16(v&0xFFFF);};
        w16(J2K_SOC);w16(J2K_SIZ);w16(47);w16(0);w32(w);w32(h);w32(0);w32(0);w32(w);w32(h);w32(0);w32(0);
        w16(3);for(int c=0;c<3;++c){w8(11);w8(1);w8(1);}
        w16(J2K_COD);w16(2+1+4+5+(NUM_DWT_LEVELS+1));w8(0);w8(1);w16(1);w8(0);
        w8(NUM_DWT_LEVELS);w8(5);w8(5);w8(0);w8(1);
        for(int i=0;i<=NUM_DWT_LEVELS;++i) w8(0xFF);
        int ns=3*NUM_DWT_LEVELS+1;
        w16(J2K_QCD);w16(2+1+2*ns);w8(0x22);
        for(int i=0;i<ns;++i){int e=std::max(0,13-i/3),m=std::max(0,0x800-i*64);w16(uint16_t((e<<11)|(m&0x7FF)));}
    }

    void cleanup_bufs() {
        if(d_data) cudaFree(d_data); d_data=nullptr;
        if(d_tmp) cudaFree(d_tmp); d_tmp=nullptr;
        if(d_input) cudaFree(d_input); d_input=nullptr;
        if(d_encoded) cudaFree(d_encoded); d_encoded=nullptr;
        if(h_input) cudaFreeHost(h_input); h_input=nullptr;
        if(h_encoded) cudaFreeHost(h_encoded); h_encoded=nullptr;
        px=0;
    }

    ~SlangJ2KEncoderImpl() {
        cleanup_bufs();
        if(d_params) cudaFree(d_params);
        if(stream) cudaStreamDestroy(stream);
    }
};


SlangJ2KEncoder::SlangJ2KEncoder()
    : _impl(std::make_unique<SlangJ2KEncoderImpl>())
{
    _initialized = _impl->init();
}

SlangJ2KEncoder::~SlangJ2KEncoder() = default;

std::vector<uint8_t>
SlangJ2KEncoder::encode(const int32_t* const xyz[3], int width, int height,
                        int64_t bit_rate, int fps, bool is_3d, bool is_4k)
{
    std::lock_guard<std::mutex> lock(_mutex);
    if (!_initialized) return {};

    int stride = width;
    size_t n = size_t(width) * height;
    int64_t fb = bit_rate / fps; if (is_3d) fb /= 2;
    size_t tt = std::max(size_t(16384), size_t(fb / 8));
    size_t tpc = (tt - 200) / 3;
    tpc = std::min(tpc, n);

    _impl->ensure(width, height, tpc);
    _impl->build_hdr(width, height);

    float bs = is_4k ? 0.5f : 1.0f;
    float steps[3] = {bs*1.2f, bs, bs*1.2f};

    /* Process each component */
    for (int c = 0; c < 3; ++c) {
        /* Upload */
        memcpy(_impl->h_input, xyz[c], n * sizeof(int32_t));
        cudaMemcpy(_impl->d_input, _impl->h_input, n * sizeof(int32_t), cudaMemcpyHostToDevice);

        /* Set up Slang global params */
        _impl->set_global_params(width, height, stride, steps[c], tpc);

        /* int -> float */
        int G = (n + 127) / 128;
        intToFloat<<<G, 128>>>();
        cudaDeviceSynchronize();

        /* DWT: 5 levels */
        int w = width, h = height;
        for (int l = 0; l < NUM_DWT_LEVELS; ++l) {
            _impl->update_params_wh(w, h);

            if (w <= 2048) {
                dwtHorzSmem<<<h, 128, w * sizeof(float)>>>();
            } else {
                dwtHorz<<<(h+127)/128, 128>>>();
            }
            cudaDeviceSynchronize();
            _impl->swap_data_tmp();

            dwtVert<<<(w+127)/128, 128>>>();
            cudaDeviceSynchronize();
            _impl->swap_data_tmp();

            w = (w+1)/2; h = (h+1)/2;
        }

        /* Quantize + encode */
        _impl->update_params_wh(width, height);
        /* Update step size and target in params */
        {
            Params_0 p;
            cudaMemcpy(&p, _impl->d_params, sizeof(Params_0), cudaMemcpyDeviceToHost);
            p.stepSize_0 = steps[c];
            p.targetN_0 = tpc;
            p.n_0 = n;
            cudaMemcpy(_impl->d_params, &p, sizeof(Params_0), cudaMemcpyHostToDevice);
        }
        /* Re-set global params to ensure encoded buffer is current */
        {
            GlobalParams_0 gp;
            cudaMemcpyFromSymbol(&gp, SLANG_globalParams, sizeof(GlobalParams_0));
            gp.g_encoded_0.data = _impl->d_encoded;
            cudaMemcpyToSymbol(SLANG_globalParams, &gp, sizeof(GlobalParams_0));
        }

        quantEncode<<<(tpc+127)/128, 128>>>();
        cudaDeviceSynchronize();

        /* Download */
        cudaMemcpy(_impl->h_encoded + c * tpc, _impl->d_encoded, tpc, cudaMemcpyDeviceToHost);
    }

    /* Assemble J2K codestream */
    std::vector<uint8_t> cs;
    size_t td = tpc * 3;
    cs.reserve(_impl->hdr.size() + 20 + td + 2);
    cs = _impl->hdr;

    auto w8=[&](uint8_t v){cs.push_back(v);};
    auto w16=[&](uint16_t v){cs.push_back(v>>8);cs.push_back(v&0xFF);};
    auto w32=[&](uint32_t v){w16(v>>16);w16(v&0xFFFF);};

    w16(J2K_SOT);w16(10);w16(0);
    size_t psot=cs.size();w32(0);w8(0);w8(1);
    w16(J2K_SOD);
    cs.insert(cs.end(), _impl->h_encoded, _impl->h_encoded + td);
    while(cs.size() < 16384) cs.push_back(0);
    uint32_t tl=uint32_t(cs.size()-psot+4);
    cs[psot]=tl>>24;cs[psot+1]=(tl>>16)&0xFF;cs[psot+2]=(tl>>8)&0xFF;cs[psot+3]=tl&0xFF;
    w16(J2K_EOC);
    return cs;
}
