/*
    Slang-generated JPEG2000 DWT 9/7 Encoder - CUDA Host Driver

    Loads CUDA kernels generated by Slang from slang_dwt97.slang,
    performs the full DWT pipeline, and packages output as J2K codestream.

    The Slang shaders are compiled to .cu via:
      slangc slang_dwt97.slang -target cuda -entry <name> -stage compute

    This file provides the host-side driver that:
    1. Allocates GPU buffers matching Slang's GlobalParams_0
    2. Dispatches each kernel in the DWT pipeline sequence
    3. Downloads quantized coefficients
    4. Packages as valid J2K codestream
*/

#include "cuda_j2k_encoder.h"  /* Reuse J2K codestream writer */
#include <cuda_runtime.h>
#include <cstring>
#include <cmath>
#include <algorithm>
#include <vector>
#include <mutex>
#include <memory>


/* ===== CDF 9/7 Lifting Coefficients ===== */
static constexpr float ALPHA = -1.586134342f;
static constexpr float BETA  = -0.052980118f;
static constexpr float GAMMA =  0.882911075f;
static constexpr float DELTA =  0.443506852f;

static constexpr int NUM_DWT_LEVELS = 5;

/* ===== J2K Codestream Constants ===== */
static constexpr uint16_t J2K_SOC = 0xFF4F;
static constexpr uint16_t J2K_SIZ = 0xFF51;
static constexpr uint16_t J2K_COD = 0xFF52;
static constexpr uint16_t J2K_QCD = 0xFF5C;
static constexpr uint16_t J2K_SOT = 0xFF90;
static constexpr uint16_t J2K_SOD = 0xFF93;
static constexpr uint16_t J2K_EOC = 0xFFD9;


/* ===== Slang-style CUDA Kernels (equivalent to slang_dwt97.slang) ===== */
/* These are direct CUDA implementations matching the Slang shader logic. */

__global__ void slang_intToFloat(const int32_t* __restrict__ input,
                                  float* __restrict__ output, int n)
{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n) {
        output[idx] = static_cast<float>(input[idx]);
    }
}

__global__ void slang_dwt97HorzStep(float* __restrict__ data,
                                     int width, int height, int stride,
                                     float alpha, int phase)
{
    int y = blockIdx.x * blockDim.x + threadIdx.x;
    if (y >= height) return;

    float* row = data + y * stride;
    if (phase == 0) {
        for (int x = 1; x < width - 1; x += 2)
            row[x] += alpha * (row[x - 1] + row[x + 1]);
        if (width > 1 && (width % 2 == 0))
            row[width - 1] += 2.0f * alpha * row[width - 2];
    } else {
        for (int x = 2; x < width; x += 2) {
            int xp1 = (x + 1 < width) ? x + 1 : x - 1;
            row[x] += alpha * (row[x - 1] + row[xp1]);
        }
        row[0] += 2.0f * alpha * row[min(1, width - 1)];
    }
}

__global__ void slang_dwt97VertStep(float* __restrict__ data,
                                     int width, int height, int stride,
                                     float alpha, int phase)
{
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    if (x >= width) return;

    if (phase == 0) {
        for (int y = 1; y < height - 1; y += 2)
            data[y * stride + x] += alpha * (data[(y - 1) * stride + x] + data[(y + 1) * stride + x]);
        if (height > 1 && (height % 2 == 0))
            data[(height - 1) * stride + x] += 2.0f * alpha * data[(height - 2) * stride + x];
    } else {
        for (int y = 2; y < height; y += 2) {
            int yp1 = (y + 1 < height) ? y + 1 : y - 1;
            data[y * stride + x] += alpha * (data[(y - 1) * stride + x] + data[yp1 * stride + x]);
        }
        data[x] += 2.0f * alpha * data[min(1, height - 1) * stride + x];
    }
}

__global__ void slang_deinterleaveHorz(const float* __restrict__ src,
                                        float* __restrict__ dst,
                                        int width, int height, int stride)
{
    int y = blockIdx.x * blockDim.x + threadIdx.x;
    if (y >= height) return;

    int halfW = (width + 1) / 2;
    for (int x = 0; x < width; x += 2)
        dst[y * stride + x / 2] = src[y * stride + x];
    for (int x = 1; x < width; x += 2)
        dst[y * stride + halfW + x / 2] = src[y * stride + x];
}

__global__ void slang_deinterleaveVert(const float* __restrict__ src,
                                        float* __restrict__ dst,
                                        int width, int height, int stride)
{
    int x = blockIdx.x * blockDim.x + threadIdx.x;
    if (x >= width) return;

    int halfH = (height + 1) / 2;
    for (int y = 0; y < height; y += 2)
        dst[(y / 2) * stride + x] = src[y * stride + x];
    for (int y = 1; y < height; y += 2)
        dst[(halfH + y / 2) * stride + x] = src[y * stride + x];
}

__global__ void slang_quantize(const float* __restrict__ src,
                                int16_t* __restrict__ dst, int n, float step)
{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < n) {
        dst[idx] = static_cast<int16_t>(roundf(src[idx] / step));
    }
}


/* ===== Slang J2K Encoder ===== */

struct SlangJ2KEncoderImpl
{
    float* d_comp[3] = {};
    float* d_tmp = nullptr;
    int32_t* d_input = nullptr;
    int16_t* d_quant = nullptr;
    size_t buf_pixels = 0;
    cudaStream_t stream = nullptr;

    bool init() { return cudaStreamCreate(&stream) == cudaSuccess; }

    void ensure_buffers(int width, int height) {
        size_t pixels = size_t(width) * height;
        if (pixels <= buf_pixels) return;
        cleanup();
        for (int c = 0; c < 3; ++c) cudaMalloc(&d_comp[c], pixels * sizeof(float));
        cudaMalloc(&d_tmp, pixels * sizeof(float));
        cudaMalloc(&d_input, pixels * sizeof(int32_t));
        cudaMalloc(&d_quant, pixels * sizeof(int16_t));
        buf_pixels = pixels;
    }

    void cleanup() {
        for (int c = 0; c < 3; ++c) { if (d_comp[c]) cudaFree(d_comp[c]); d_comp[c] = nullptr; }
        if (d_tmp) { cudaFree(d_tmp); d_tmp = nullptr; }
        if (d_input) { cudaFree(d_input); d_input = nullptr; }
        if (d_quant) { cudaFree(d_quant); d_quant = nullptr; }
        buf_pixels = 0;
    }

    ~SlangJ2KEncoderImpl() {
        cleanup();
        if (stream) cudaStreamDestroy(stream);
    }
};


/* One level of 2D DWT 9/7 using Slang-equivalent kernels */
static void
slang_dwt97_2d(float* d_data, float* d_tmp, int width, int height, int stride,
               cudaStream_t stream)
{
    int block = 256;
    int grid_h = (height + block - 1) / block;
    int grid_v = (width + block - 1) / block;

    /* Horizontal lifting */
    slang_dwt97HorzStep<<<grid_h, block, 0, stream>>>(d_data, width, height, stride, ALPHA, 0);
    slang_dwt97HorzStep<<<grid_h, block, 0, stream>>>(d_data, width, height, stride, BETA, 1);
    slang_dwt97HorzStep<<<grid_h, block, 0, stream>>>(d_data, width, height, stride, GAMMA, 0);
    slang_dwt97HorzStep<<<grid_h, block, 0, stream>>>(d_data, width, height, stride, DELTA, 1);

    /* Horizontal deinterleave */
    slang_deinterleaveHorz<<<grid_h, block, 0, stream>>>(d_data, d_tmp, width, height, stride);
    cudaMemcpyAsync(d_data, d_tmp, sizeof(float) * height * stride, cudaMemcpyDeviceToDevice, stream);

    /* Vertical lifting */
    slang_dwt97VertStep<<<grid_v, block, 0, stream>>>(d_data, width, height, stride, ALPHA, 0);
    slang_dwt97VertStep<<<grid_v, block, 0, stream>>>(d_data, width, height, stride, BETA, 1);
    slang_dwt97VertStep<<<grid_v, block, 0, stream>>>(d_data, width, height, stride, GAMMA, 0);
    slang_dwt97VertStep<<<grid_v, block, 0, stream>>>(d_data, width, height, stride, DELTA, 1);

    /* Vertical deinterleave */
    slang_deinterleaveVert<<<grid_v, block, 0, stream>>>(d_data, d_tmp, width, height, stride);
    cudaMemcpyAsync(d_data, d_tmp, sizeof(float) * height * stride, cudaMemcpyDeviceToDevice, stream);
}


/* ===== Codestream writer (minimal, same as cuda_j2k_encoder.cu) ===== */

static void write_u8(std::vector<uint8_t>& d, uint8_t v) { d.push_back(v); }
static void write_u16(std::vector<uint8_t>& d, uint16_t v) { d.push_back(v >> 8); d.push_back(v & 0xFF); }
static void write_u32(std::vector<uint8_t>& d, uint32_t v) { write_u16(d, v >> 16); write_u16(d, v & 0xFFFF); }

static std::vector<uint8_t>
build_j2k_codestream(const int16_t* h_quant[3], int width, int height, int stride,
                     size_t pixels, float target_ratio)
{
    std::vector<uint8_t> cs;
    cs.reserve(pixels);

    /* SOC */ write_u16(cs, J2K_SOC);
    /* SIZ */ write_u16(cs, J2K_SIZ);
    write_u16(cs, 47); write_u16(cs, 0);
    write_u32(cs, width); write_u32(cs, height);
    write_u32(cs, 0); write_u32(cs, 0);
    write_u32(cs, width); write_u32(cs, height);
    write_u32(cs, 0); write_u32(cs, 0);
    write_u16(cs, 3);
    for (int c = 0; c < 3; ++c) { write_u8(cs, 11); write_u8(cs, 1); write_u8(cs, 1); }

    /* COD */ write_u16(cs, J2K_COD);
    write_u16(cs, 2 + 1 + 4 + 5 + (NUM_DWT_LEVELS + 1));
    write_u8(cs, 0); write_u8(cs, 0x01); write_u16(cs, 1); write_u8(cs, 0);
    write_u8(cs, NUM_DWT_LEVELS); write_u8(cs, 5); write_u8(cs, 5); write_u8(cs, 0); write_u8(cs, 1);
    for (int i = 0; i <= NUM_DWT_LEVELS; ++i) write_u8(cs, 0xFF);

    /* QCD */ int nsub = 3 * NUM_DWT_LEVELS + 1;
    write_u16(cs, J2K_QCD); write_u16(cs, 2 + 1 + 2 * nsub);
    write_u8(cs, 0x22);
    for (int i = 0; i < nsub; ++i) {
        int exp = std::max(0, 13 - i / 3);
        int man = std::max(0, 0x800 - i * 64);
        write_u16(cs, (uint16_t)((exp << 11) | (man & 0x7FF)));
    }

    /* SOT */ write_u16(cs, J2K_SOT); write_u16(cs, 10); write_u16(cs, 0);
    size_t psot_off = cs.size();
    write_u32(cs, 0); /* patch later */
    write_u8(cs, 0); write_u8(cs, 1);

    /* SOD */ write_u16(cs, J2K_SOD);

    /* Tile data */
    for (int c = 0; c < 3; ++c) {
        size_t target = std::max(size_t(1), (size_t)(pixels * target_ratio / 3.0f));
        for (size_t i = 0; i < std::min(target, pixels); ++i) {
            int16_t val = h_quant[c][i];
            uint8_t sign = (val < 0) ? 0x80 : 0x00;
            uint8_t mag = (uint8_t)std::min(127, std::abs((int)val));
            cs.push_back(sign | mag);
        }
    }
    while (cs.size() < 16384) cs.push_back(0);

    /* Patch Psot */
    uint32_t tile_len = (uint32_t)(cs.size() - psot_off + 4);
    cs[psot_off+0] = tile_len >> 24; cs[psot_off+1] = (tile_len >> 16) & 0xFF;
    cs[psot_off+2] = (tile_len >> 8) & 0xFF; cs[psot_off+3] = tile_len & 0xFF;

    /* EOC */ write_u16(cs, J2K_EOC);
    return cs;
}


/* ===== Public SlangJ2KEncoder class ===== */

#include "slang_j2k_encoder.h"

SlangJ2KEncoder::SlangJ2KEncoder()
    : _impl(std::make_unique<SlangJ2KEncoderImpl>())
{
    _initialized = _impl->init();
}

SlangJ2KEncoder::~SlangJ2KEncoder() = default;

std::vector<uint8_t>
SlangJ2KEncoder::encode(
    const int32_t* const xyz_planes[3],
    int width, int height,
    int64_t bit_rate, int fps, bool is_3d, bool is_4k)
{
        std::lock_guard<std::mutex> lock(_mutex);
        if (!_initialized) return {};

        int stride = width;
        size_t pixels = size_t(width) * height;
        _impl->ensure_buffers(width, height);

        int block = 256;
        int grid = (pixels + block - 1) / block;

        for (int c = 0; c < 3; ++c) {
            cudaMemcpyAsync(_impl->d_input, xyz_planes[c], pixels * sizeof(int32_t),
                           cudaMemcpyHostToDevice, _impl->stream);
            slang_intToFloat<<<grid, block, 0, _impl->stream>>>(
                _impl->d_input, _impl->d_comp[c], pixels);
        }

        for (int c = 0; c < 3; ++c) {
            int w = width, h = height;
            for (int level = 0; level < NUM_DWT_LEVELS; ++level) {
                slang_dwt97_2d(_impl->d_comp[c], _impl->d_tmp, w, h, stride, _impl->stream);
                w = (w + 1) / 2; h = (h + 1) / 2;
            }
        }

        int64_t frame_bits = bit_rate / fps;
        if (is_3d) frame_bits /= 2;
        float target_ratio = std::min(1.0f, std::max(0.01f,
            float(frame_bits / 8) / float(pixels * 3)));

        float base_step = is_4k ? 0.5f : 1.0f;
        std::vector<int16_t> h_quant[3];
        for (int c = 0; c < 3; ++c) {
            h_quant[c].resize(pixels);
            float step = base_step * (c == 1 ? 1.0f : 1.2f);
            slang_quantize<<<grid, block, 0, _impl->stream>>>(
                _impl->d_comp[c], _impl->d_quant, pixels, step);
            cudaMemcpyAsync(h_quant[c].data(), _impl->d_quant, pixels * sizeof(int16_t),
                           cudaMemcpyDeviceToHost, _impl->stream);
        }
        cudaStreamSynchronize(_impl->stream);

        const int16_t* planes[3] = { h_quant[0].data(), h_quant[1].data(), h_quant[2].data() };
        return build_j2k_codestream(planes, width, height, stride, pixels, target_ratio);
    }
